version: '3'

networks:
  site-network:

services:
  site:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - site-network

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    # ports:
      # - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - site-network

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html:rw
    ports:
      - "9000:9000"
    networks:
      - site-network

  adminer:
    image: adminer
    restart: always
    networks:
      - site-network
    depends_on:
      - mysql
    ports:
      - 8081:8080
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=512M
    restart: always
    ports:
      - 8082:80
    networks:
      - site-network
    depends_on:
        - mysql
    volumes:
      - /sessions
